=== justinkim12/XML_JAVA_Project/src/data_DTDver.dtd
<!ELEMENT travel (user_table,guide_table,travel_product_info,place_info) >
<!ELEMENT user_table (user*) >
<!ELEMENT user (user_name,age?,favorite_city,following_guide,Bookmark) >
<!ATTLIST user id CDATA #REQUIRED>
<!ATTLIST user sex (male | female) "male">
<!ELEMENT user_name (#PCDATA) >
<!ELEMENT age (#PCDATA) >
<!ELEMENT favorite_city (city+) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT following_guide (guide_id*) >
<!ELEMENT Bookmark (product_id*) >
<!ELEMENT product_id (#PCDATA) >
<!ELEMENT guide_id (#PCDATA) >
<!ELEMENT guide_table (guide*) >
<!ELEMENT guide (guide_name,age?,followers,travel_product_list) >
<!ATTLIST guide id CDATA #REQUIRED>
<!ELEMENT guide_name (#PCDATA) >
<!ELEMENT travel_product_list (product_id+) >
<!ELEMENT followers (#PCDATA) >
<!ELEMENT travel_product_info (travel_product*) >
<!ELEMENT travel_product (city,guide_id,cost,course) >
<!ATTLIST travel_product id CDATA #REQUIRED>
<!ELEMENT course (place_name+) >
<!ATTLIST course theme CDATA #IMPLIED>
<!ELEMENT place_name (#PCDATA) >
<!ELEMENT cost (#PCDATA) >
<!ELEMENT place_info (place*) >
<!ELEMENT place (place_name,hashtag_list) >
<!ATTLIST place city CDATA #REQUIRED>
<!ELEMENT hashtag_list (hashtag+) >
<!ELEMENT hashtag (#PCDATA) >

=== justinkim12/XML_JAVA_Project/src/data_DTDver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE travel SYSTEM "data_DTDver.dtd">

<travel>
<!-- user_table --><!-- user_table -->
    <user_table>
        <user id="1">
            <user_name>Tom</user_name>

            <age>21</age>
            
            <favorite_city>
                <city>Busan</city>
            </favorite_city>

            <following_guide>
                <guide_id>1</guide_id>
                <guide_id>2</guide_id>
            </following_guide>

            <Bookmark>
                <product_id>1</product_id>
            </Bookmark>
        </user>
        <user id="2">
            <user_name>Ale</user_name>

            <age>22</age>
            
            <favorite_city>
                <city>Seoul</city>

            </favorite_city>

            <following_guide>
                <guide_id>2</guide_id>
            </following_guide>

            <Bookmark></Bookmark>
        </user>
        
        <user id="3">
            <user_name>Wan</user_name>

            <age>32</age>
            
            <favorite_city>
                <city>Incheon</city>

            </favorite_city>

            <following_guide>
                <guide_id>3</guide_id>
                <guide_id>9</guide_id>
            </following_guide>

            <Bookmark>
                <product_id>9</product_id>
            </Bookmark>
        </user>
        
        <user id="4">
            <user_name>Ron</user_name>

            <age>20</age>
            
            <favorite_city>
                <city>Gangneung</city>
            </favorite_city>

            <following_guide>
                <guide_id>4</guide_id>
                <guide_id>10</guide_id>
            </following_guide>

            <Bookmark></Bookmark>
        </user>
        
        <user id="5">
            <user_name>Ian</user_name>
            
            <favorite_city>
                <city>Jeju</city>

            </favorite_city>

            <following_guide>
                <guide_id>5</guide_id>
            </following_guide>

            <Bookmark>
                <product_id>5</product_id>
            </Bookmark>
        </user>
                
        <user id="6">
            <user_name>Bob</user_name>
            
            <favorite_city>
                <city>Busan</city>
                <city>Yeosu</city>
            </favorite_city>

            <following_guide>
                <guide_id>6</guide_id>
            </following_guide>

            <Bookmark>
                <product_id></product_id>
            </Bookmark>
        </user>
        
        <user id="7">
            <user_name>Chang</user_name>

            <age>25</age>
            
            <favorite_city>
                <city>Gongju</city>

            </favorite_city>

            <following_guide>
                <guide_id>7</guide_id>
            </following_guide>

            <Bookmark></Bookmark>
        </user>
        
        <user id="8" sex="female"> 
            <user_name>Amy</user_name>

            <age>20</age>
            
            <favorite_city>
                <city>Seoul</city>
            </favorite_city>

            <following_guide>
                <guide_id>2</guide_id>
                <guide_id>12</guide_id>
            </following_guide>

            <Bookmark></Bookmark>
        </user>
        
        <user id="9">
            <user_name>Paul</user_name>
            
            <favorite_city>
                <city>Busan</city>

            </favorite_city>

            <following_guide>
                <guide_id>1</guide_id>
                <guide_id>11</guide_id>
            </following_guide>

            <Bookmark></Bookmark>
        </user>
                
        <user id="10">
            <user_name>Naem</user_name>

            <age>31</age>
            
            <favorite_city>
                <city>Jeju</city>
                <city>Jeonju</city>
            </favorite_city>

            <following_guide>
                <guide_id>5</guide_id>
                <guide_id>8</guide_id>
            </following_guide>

            <Bookmark></Bookmark>
        </user>
                
        <user id="11">
            <user_name>Tim</user_name>

            <age>30</age>
            
            <favorite_city>
                <city>Jeju</city>
            </favorite_city>

            <following_guide>
                <guide_id>5</guide_id>
            </following_guide>

            <Bookmark></Bookmark>
        </user>
        
        <user id="12">
            <user_name>Kane</user_name>

            <age>19</age>
            
            <favorite_city>
                <city>Busan</city>
            </favorite_city>

            <following_guide>
                <guide_id>1</guide_id>
            </following_guide>

            <Bookmark>
                <product_id>11</product_id>
            </Bookmark>
        </user>
        <user id="13">
            <user_name>Roo</user_name>
            
            <favorite_city>
                <city>Seoul</city>

            </favorite_city>

            <following_guide>
                <guide_id>2</guide_id>
            </following_guide>

            <Bookmark></Bookmark>
        </user>
        
        <user id="14" sex='female'>
            <user_name>Susan</user_name>

            <age>17</age>
            
            <favorite_city>
                <city>Yeosu</city>

            </favorite_city>

            <following_guide></following_guide>

            <Bookmark></Bookmark>
        </user>
        
        <user id="15">
            <user_name>Ryan</user_name>

            <age>22</age>
            
            <favorite_city>
                <city>Gongju</city>

            </favorite_city>

            <following_guide></following_guide>

            <Bookmark></Bookmark>
        </user>
    </user_table>    
<!-- user_table -->
<!-- user_table --><!-- user_table -->

<!-- guide_table --><!-- guide_table -->

    <guide_table>

        <guide id="1">
            <guide_name>Kim</guide_name>
            
            <age>30</age>
            
            <followers>3</followers>

            <travel_product_list>
                <product_id>1</product_id>
            </travel_product_list>
        </guide>

        <guide id="2">
            <guide_name>Lee</guide_name>
            
            <age>31</age>
            
            <followers>4</followers>

            <travel_product_list>
                <product_id>2</product_id>
                <product_id>13</product_id>
            </travel_product_list>
        </guide>

        <guide id="3">
            <guide_name>Park</guide_name>
            
            <age>28</age>
            
            <followers>1</followers>

            <travel_product_list>
                <product_id>3</product_id>
            </travel_product_list>
        </guide>

        <guide id="4">
            <guide_name>Choi</guide_name>
            
            <age>27</age>
            
            <followers>1</followers>

            <travel_product_list>
                <product_id>4</product_id>
            </travel_product_list>
        </guide>

        <guide id="5">
            <guide_name>Moon</guide_name>
                        
            <followers>3</followers>

            <travel_product_list>
                <product_id>5</product_id>
            </travel_product_list>
        </guide>

        <guide id="6">
            <guide_name>Jung</guide_name>
                        
            <followers>1</followers>

            <travel_product_list>
                <product_id>6</product_id>
            </travel_product_list>
        </guide>

        <guide id="7">
            <guide_name>Kang</guide_name>
            
            <age>31</age>
            
            <followers>1</followers>

            <travel_product_list>
                <product_id>7</product_id>
            </travel_product_list>
        </guide>

        <guide id="8">
            <guide_name>Ryu</guide_name>
            
            <age>30</age>
            
            <followers>1</followers>

            <travel_product_list>
                <product_id>8</product_id>
            </travel_product_list>
        </guide>

        <guide id="9">
            <guide_name>Han</guide_name>
            
            <age>29</age>
            
            <followers>1</followers>

            <travel_product_list>
                <product_id>9</product_id>
            </travel_product_list>
        </guide>

        <guide id="10">
            <guide_name>Nam</guide_name>
                        
            <followers>1</followers>

            <travel_product_list>
                <product_id>10</product_id>
            </travel_product_list>
        </guide>

        <guide id="11">
            <guide_name>Joo</guide_name>
            
            <age>28</age>
            
            <followers>1</followers>

            <travel_product_list>
                <product_id>11</product_id>
            </travel_product_list>
        </guide>

        <guide id="12">
            <guide_name>Yang</guide_name>
            
            <age>29</age>
            
            <followers>1</followers>

            <travel_product_list>
                <product_id>12</product_id>
            </travel_product_list>
        </guide>

    </guide_table>
<!-- guide_table -->
<!-- guide_table --><!-- guide_table -->


<!-- <travel_product_info> --><!-- <travel_product_info> -->
    <travel_product_info>
        <travel_product id="1">
            <city>Busan</city>

            <guide_id>1</guide_id>

            <cost>14</cost>

            <course theme="Healing">
                <place_name>HaeWoonDae</place_name>
                <place_name>GwangAnLee</place_name>
                <place_name>JaGalChi</place_name>
            </course>
        </travel_product>

        <travel_product id="2">
